### ISSUE TITLE
Ошибка компиляции под микроконтроллер Atmega32u4.

### ISSUE THREAD

**Issue by telephonist95** [GyverLibs/GyverPower#1]
Строка 104, текст ошибки: **_error: 'sleep_bod_disable' was not declared in this scope._**
Для микронтроллера 32u4 в avr/sleep.h не определена функция sleep_bod_disable. Как вариант решения - добавить проверку на макросы **_BODS_** и **_BODSE_** в методе sleep:
```c++
if (bodEnable){
    interrupts();
    sleep_cpu ();
} else {
#if defined(BODS) && defined(BODSE)
    noInterrupts();
    sleep_bod_disable();
#endif
    interrupts();
    sleep_cpu ();
}
```

**Comment by GyverLibs** [comment]
спасибо! выкатил апдейт
